### ISSUE TITLE
Cannot build container

### ISSUE THREAD

**Issue by RLovelett** [norio-nomura/docker-sourcekit-builder#1]
Running the first command in the `README` (e.g., `docker build -t sourcekit-builder:3020160725a https://github.com/norio-nomura/docker-sourcekit-builder.git`) ends with:

```
utils/build-script: fatal error: preset 'buildbot_linux_libdispatch' not found
The command '/bin/sh -c git clone https://github.com/norio-nomura/swift-dev.git &&     cd ${WORK_DIR} &&     git fetch &&     git checkout ${REVISION} &&     git submodule update --init --recursive &&     cd ${SRC_DIR} &&     utils/build-script --preset="buildbot_linux_libdispatch"       install_destdir="${SWIFT_INSTALL_DIR}" &&     utils/build-script --preset="buildbot_linux"       install_destdir="${SWIFT_INSTALL_DIR}"       installable_package="${SWIFT_INSTALLABLE_PACKAGE}" &&     cd / &&     tar zxvf "${SWIFT_INSTALLABLE_PACKAGE}" -C / &&     rm -rf ${WORK_DIR}' returned a non-zero code: 1
```

Suggestions?

**Comment by norio-nomura** [comment]
Thank you for trying!
I'm updating to using `swift-DEVELOPMENT-SNAPSHOT-2016-07-25-a` and caused this issue.
I reverted `master` back to commit that I succeeded to build.
Could you please try again?

**Comment by norio-nomura** [comment]
> I reverted master back to commit that I succeeded to build.
> Could you please try again?

It also reverted `README.md` and that building steps are different on tag for image.

**Comment by norio-nomura** [comment]
I just updated to `swift-DEVELOPMENT-SNAPSHOT-2016-07-25-a` and fixed this issue.

**Comment by RLovelett** [comment]
Thank you!

**Comment by norio-nomura** [comment]
I updated `norionomura/sourcekit:3020160725a` image for fixing runtime error of lldb.
If you already pulled the image, I recommend you to pull that again.
Sorry for inconvenience.
