### ISSUE TITLE
<unknown>:0: error: unable to load standard library for target 'x86_64-unknown-linux-gnu'

### ISSUE THREAD

**Issue by norio-nomura** [norio-nomura/docker-sourcekit-builder#3]
Following error produced by `/usr/lib/sourcekitdInProc.framework/sourcekitdInProc` on Swift 3.1:
> <unknown>:0: error: unable to load standard library for target 'x86_64-unknown-linux-gnu'

**Comment by jpsim** [comment]
This is probably a mistake in the Swift packaging, since `.framework`s aren't a convention on Linux.

**Comment by norio-nomura** [comment]
This issue has been fixed on https://github.com/norio-nomura/docker-sourcekit-builder/releases/tag/311
